name: CI Build-
on :
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
  services:
      redis:
        image: redis:6-alpine
steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run:
          python -m pip install --upgrade pip wheel pip install -r requirements.txt
      - name: Run unit tests with nose
        run: nosetests
        env:
          DATABASE._URI: redis://redis:6379
      - name: Upload code coverage
        users: codecov/codecov-actionlv2
        with:
          version: *v0.1.13*